<?php
/**
 * Created by PhpStorm.
 * User: ALEX
 * Date: 14.04.2018
 * Time: 12:41
 */

namespace app\modules\admin\controllers;


use yii\web\Controller;
use yii\filters\AccessControl;

class AppAdminController extends Controller {

    public function behaviors()
    {

        return [
            'access' => [
                'class' => AccessControl::className(),
                //'only' => ['login', 'logout', 'signup'],
                'rules' => [

                    [
                        'allow' => true,
                        'actions' => ['index','post','create','view','update','delete','deletemoreimg','uploadfiles','changeposition'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

        //return parent::behaviors(); // TODO: Change the autogenerated stub


}